### ISSUE TITLE
HF hosted model details

### ISSUE THREAD

**Issue by mllife** [DS4SD/docling-ibm-models#23]
I see in the config file [/model_artifacts/tableformer/tm_config.json](https://huggingface.co/ds4sd/docling-models/blob/main/model_artifacts/tableformer/tm_config.json) the dataset name mentioned is "name": "PubTabNet_300_100_512". Is this the best model you have trained? Any model based on "FinTabNet"? Or is it going to be shared in future?

I see in the paper published [https://arxiv.org/pdf/2203.01017](https://arxiv.org/pdf/2203.01017) you have shared the benchmarks on different datasets. Is the same model shared in HF used for all the evaluations?

**Comment by maxmnemonic** [comment]
The name in the configuration is a relic from early development, sorry for that :)
In fact, after TF paper that you mentioned we did more work and trainings outlined in OTSL paper: [Optimized Table Tokenization for Table Structure Recognition](https://arxiv.org/abs/2305.03393)

Additionally to the Pub1M, FinTabNet, PubTabNet, SynthTabNet that we mention in our papers, ths model that we published was trained on [WikiTableSet](https://github.com/namtuanly/WikiTableSet)

**Comment by mllife** [comment]
Any chance, Can you share the model checkpoint for FinTabNet dataset? As it's the most varied set of examples I have personally explored and should be applicable to most of the users.

**Comment by nikos-livathinos** [comment]
@mllife we share the TableFormer checkpoint trained on all datasets (including FinTabNet) on HuggingFace: https://huggingface.co/ds4sd/docling-models/tree/main/model_artifacts/tableformer

**Comment by mllife** [comment]
@nikos-livathinos , what do this mean, "this model that we published was trained on [WikiTableSet](https://github.com/namtuanly/WikiTableSet)", it is contradictory?
