### ISSUE TITLE
Enhancement: Install torch for CPU by default

### ISSUE THREAD

**Issue by benjamin-callonnec** [DS4SD/docling-ibm-models#60]
Hello,

Would it possible to let the user choose whether he wants to install `docling-ibm-models` only with cpu dependencies or with gpu dependencies? 

Thank you!

**Comment by sanmai-NL** [comment]
Isn't this a concern of the package manager? See e.g., `uv`'s instructions: https://docs.astral.sh/uv/guides/integration/pytorch/#using-a-pytorch-index

**Comment by benjamin-callonnec** [comment]
You are right in my package, using poetry i could do something like this 

```text
torch = {version = "^2.5.1+cpu", source = "pytorch_cpu"}
torchvision = {version = "^0.20.1+cpu", source = "pytorch_cpu"}

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```

Thank you for the suggestion!
